### PR TITLE
Fixed docs introduction.

### PR DESCRIPTION
**Pull request by anderejd**
I'm guessing this is more like what was intended.

### CODE REVIEW

**Comment by shepmaster** [comment]
@carllerche looks like Travis [flagged this PR as potential abuse](https://travis-ci.org/carllerche/tower-web/requests) — you may need to poke at it to unstick it.

**Comment by carllerche** [comment]
I don't see a way to unflag it as abuse.

**Comment by shepmaster** [comment]
Everything I see says to email support@travis-ci.com. TBH, I've never even seen this before.

**Comment by carllerche** [comment]
Yeah, I emailed... if they don't get back soon, I will force merge.

**Comment by carllerche** [comment]
I received:

> Looking at the requests tab, the GitHub user anderejd seems to have never logged into Travis CI and this is why we are currently blocking your requests. Sorry for the inconvenience.
> 
> To confirm, can you please ask anderejd to try logging into Travis CI at least once at https://travis-ci.org/ and push a new commit?

**Comment by anderejd** [comment]
I've never used Travis, should I?

**Comment by anderejd** [comment]
> Hi anderejd -
>
> Thanks for your email and for your patience. Sorry for the confusion.
>
> Our system automatically flagged your account for possible abuse, but after further review, we were able to clear that up. You should be all set to build as normal, though please feel free to contact us should you have any questions or concerns arise.
>
> Thanks again!
> Carla

Looks like it should work now. That was the most time consuming single line of comment code I have ever produced ^^

**Comment by shepmaster** [comment]
@anderejd can you try rebasing your commit and pushing it to your branch? I expect that to trigger another build.

**Comment by anderejd** [comment]
Rebased on master.

**Comment by shepmaster** [comment]
A very hard-earned comma removal! 😉

**Comment by anderejd** [comment]
Hey don't be condescending now, might I remind you that I also added a single letter word.

**Pull request merged**
