### PR TITLE
tower-web-macros: add a #[web(either)] mode for enums

### LINKED ISSUE #89: Returning different response types from the same handler
E.g. I want to return either a `File` or an HTML page. I could probably make do with an enum that implements `Response`, but the `File` and `String` impls have different item types, so it's awkward.

Is there anything `tower-web` can do to make this easier?

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #89.

### CODE REVIEW

**Comment by lnicola** [comment]
Added some documentation and tests.

I noticed that the macro panics when an enum has one variant with unnamed fields and one with named ones. That comes from `fold_fields_unnamed`, but I'm not sure what those functions do.

--

Besides that, the other `web` attributes are not supported. They could probably be made to work, but I'm not sure whether we want them to. Any opinions?

**Comment by carllerche** [comment]
This looks great 👍 . Only thing left is the attribute.

I don't love either option (`either` and `passthrough`). I don't have a better idea yet.

If we don't come up w/ a good name soon, we can run with `passthrough` initially and change it later.

**Comment by lnicola** [comment]
Transparent?

I think this still needs some checks that other attributes are not present. I'm not yet sure how to do that.

**Comment by carllerche** [comment]
Well, I think at *some* point it would be OK to support specifying the status code, headers, etc.. directly on the enum, so I wouldn't worry about that yet.

**Comment by lnicola** [comment]
Shouldn't we report an error just in case?

**Comment by carllerche** [comment]
If you want to do it, go for it :)

At the end of [this](https://github.com/carllerche/tower-web/pull/97/files#diff-a82a3403a4d62cf38302a8c42262559bR56) loop, you could probably just check that all the other vars were not set.

**Pull request merged**
