### PR TITLE
Prevent duplicate routes in compile time

### LINKED ISSUE #135: Disallow repeating the same route for multiple endpoints in a resource
On one of my resources, `ApiService`, I have the following impl:

```rust
        #[get("/api/company/:id")]
        #[content_type("application/json")]
        fn get_single_company(&self, id: u32) -> Result<SingleCompanyResponse, ()> {
            Ok(SingleCompanyResponse {
                item: Company { id, display_name: "Target".into(), aliases: vec![] }
            })
        }

        #[get("/api/company/:id")]
        #[content_type("application/json")]
        fn get_single_country(&self, id: u32) -> Result<SingleCountryResponse, ()> {
            Ok(SingleCountryResponse {
                item: Country { id, display_name: "Canada".into(), tags: vec![] }
            })
        }
```

The routes being duplicate is a copy & paste issue but I received no warning or error.
This can lead to confusion and lost time.

It would be useful to error (or at least warn) in this scenario if at all possible.

### PR DESCRIPTION
**Pull request by Abogical**
Fixes #135 . I haven't figured out how to write the test though, any help?

### CODE REVIEW

**Comment by carllerche** [comment]
@Abogical looks good to me. It also does seem like you got a test. I'm happy to merge if you are (still have WIP in the title).

**Comment by Abogical** [comment]
The test just doesn't work that's why I'm putting it in WIP. testing it outside the crate with impl_web! macro works, but directly calling the function `expand_derive_resource` doesn't. I'm not familiar with the codebase as you are. What am I missing?

**Comment by Abogical** [comment]
Also travis doesn't test the macros, I've opened a new issue. (#197)

**Comment by Abogical** [comment]
Test is fixed now. You can merge.

**Comment by lnicola** [comment]
Was this technically a breaking change?

**Comment by carllerche** [comment]
unsure... the original behavior was not defined.

**Comment by lnicola** [comment]
Undefined as in UB, or undefined as in "happened to pick one of the handlers"? If the latter, it sounds like a breaking change, not that I have anything against it.

**Comment by carllerche** [comment]
happened to pick one of the handlers.

I did not consider the breaking change aspect. At this point, i would leave it unless there is a report.

**Pull request merged**
