### PR TITLE
Edition 2018 updates

### LINKED ISSUE #37: tower-web's macros replace serde-derive's
After adding 

```rust
#[macro_use]
extern crate tower_web;
```

I now get this on my import of `serde_derive`

```
warning: unused `#[macro_use]` import
  --> src/main.rs:14:1
   |
14 | #[macro_use]
   | ^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default
```

### PR DESCRIPTION
**Pull request by elpiel**
- removes `extern crate`
- removes `#[macro_use]` attributes
- applies the modules system changes from 2018 edition, removing the `mod.rs` file

Opened questions:
- Should we update all the code (including docs) to use 2018 edition?

TODOs:

- ~Remove other `extern crate` + `#[macro_use]`~ Done

Maybe Resolves #37

### CODE REVIEW

**Comment by elpiel** [comment]
Build is not triggered or something + the opened question still remains, but I guess this can also be reviewed already

**Comment by elpiel** [comment]
@carllerche is it possible to continue with this? I would like to continue with making `async/await` working again with latest nightly and the `.await` syntax

**Comment by lnicola** [comment]
@elpiel sorry for not looking into this earlier, it kinda' slipped off my mind. I'm not sure if you're still using `tower-web`. I guess everyone is now waiting for `await` to hit stable, and @carllerche is busy updating `tokio` and other parts of the ecosystem.

**Comment by elpiel** [comment]
@lnicola we are thinking of migrating, because of various of reasons, but I will be happy to help more to migrate to `.await` and I will definitely be happy if this gets merged.

**Comment by lnicola** [comment]
Yeah, I was using `tower-web` myself in a small app, but I've migrated back to `hyper`, since I didn't get that much benefit from it.

Can you try pushing a small commit to kick Travis?

**Comment by elpiel** [comment]
Nightly is failing, but that's expected.

**Comment by lnicola** [comment]
Looks like all of them are failing?

> error[E0658]: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future

And a double semicolon.

**Comment by elpiel** [comment]
Yeah, by bad, actually it needs `use serde::Serialize`, but I now get another error trying to build the `test_suits`:
```error: proc-macro derive panicked
   --> src/lib.rs:494:1
    |
494 | / proc_macro_item_decl! {
495 | |     #[doc(hidden)]
496 | |     derive_resource! => derive_resource_impl
497 | | }
    | |_^
    |
    = help: message: assertion failed: `(left == right)`
              left: `Some("#[allow(unused,")`,
             right: `Some("#[allow(unused")`
```

**Comment by lnicola** [comment]
I don't see that.

**Comment by lnicola** [comment]
I don't see that with

```diff
diff --git i/src/middleware/cors/config.rs w/src/middleware/cors/config.rs
index ea9d3dc..2b09946 100644
--- i/src/middleware/cors/config.rs
+++ w/src/middleware/cors/config.rs
@@ -188,7 +188,7 @@ impl Config {
     }
 
     fn common_headers(&self, origin: HeaderValue) -> HeaderMap {
-        let mut headers = self.basic_headers();;
+        let mut headers = self.basic_headers();
 
         if self.allow_credentials {
             headers.insert(header::ACCESS_CONTROL_ALLOW_ORIGIN, origin);
diff --git i/tower-web-macros/src/derive/response.rs w/tower-web-macros/src/derive/response.rs
index 079b981..9c8504c 100644
--- i/tower-web-macros/src/derive/response.rs
+++ w/tower-web-macros/src/derive/response.rs
@@ -380,7 +380,7 @@ impl Response {
         let shadow_data = &self.shadow_ty;
 
         quote! {
-            #[derive(Serialize)]
+            #[derive(serde::Serialize)]
             #[serde(remote = #ty)]
             #shadow_data
         }
```

**Comment by elpiel** [comment]
Yes, this is true. I was trying to fix the build another way.

**Comment by lnicola** [comment]
I think there are still some unused import warnings (for `serde::Serialize`). Might be a good idea to fix those, if it's easy.

I actually wasn't sure that `#[derive(serde::Serialize)]` works, but it might be a better approach than an `use` statement. Although should it be  `__tw::codegen::serde::Serialize` instead?

**Comment by elpiel** [comment]
I think now that it is importing serde rather than having a use statement, it will trigger some unused imports indeed.

`Although should it be __tw::codegen::serde::Serialize instead?`
I have no idea, I've just started with macros and cannot give any answer

**Comment by lnicola** [comment]
Can you also bump the compiler version to 1.34 in `.travis.yml`?

**Comment by lnicola** [comment]
The CI is happy now, and is @carllerche is probably missing, so I think I'll merge this. Thanks!

**Pull request merged**
